preload = /home/rifatr/.config/hypr/images/an_astronaut_playing_a_piano.png
splash = false

wallpaper {
  monitor = HDMI-A-1
  path = /home/rifatr/.config/hypr/images/an_astronaut_playing_a_piano.png
}

wallpaper {
  monitor = DP-3
  path = /home/rifatr/.config/hypr/images/an_astronaut_playing_a_piano.png
}
