# 1. Use the FULL path (No quotes, start with /home/...)
preload = /home/rifatr/.config/hypr/images/an_astronaut_playing_a_piano.png

# 2. The comma is CRITICAL. It tells Hyprpaper "apply to ALL monitors"
wallpaper = ,/home/rifatr/.config/hypr/images/an_astronaut_playing_a_piano.png

splash = false
